project:
  type: book
  output-dir: ../../docs/vi

book:
  title: "Cuốn Sách Nhỏ về Đại Số Tuyến Tính"
  subtitle: "Phiên bản 0.3.0"
  author: "Duc-Tam Nguyen"
  date: "2025-09-26"
  output-file: book
  chapters:
    - index.qmd
    - book.qmd
    - lab.qmd

website:
  title: "Cuốn Sách Nhỏ về Đại Số Tuyến Tính"
  page-navigation: true
  navbar:
    search: true
    right:
      - text: "English"
        href: ../../index.html
      - text: "Español"
        href: ../es/index.html
      - text: "中文"
        href: ../zh-CN/index.html
      - text: "Tiếng Việt"
        href: ../vi/index.html
      - text: "日本語"
        href: ../ja/index.html
      - text: "한국어"
        href: ../ko/index.html

      - icon: github
        href: https://github.com/little-book-of/linear-algebra
        aria-label: GitHub

format:
  html:
    sidebar: true
    toc: true
    toc-location: left
    toc-depth: 3
    number-sections: false
    theme: [cosmo, brand]
